---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: centos-5.11
- name: centos-6.6
- name: debian-6.0.10
  run_list: [ "recipe[apt]" ]
- name: debian-7.7
  run_list: [ "recipe[apt]" ]
- name: fedora-19
- name: fedora-20
- name: freebsd-10.0
- name: ubuntu-10.04
  run_list: [ "recipe[apt]" ]
- name: ubuntu-12.04
  run_list: [ "recipe[apt]" ]
- name: ubuntu-14.04
  run_list: [ "recipe[apt]" ]

suites:
- name: default
  data_bags_path: "test/kitchen/data_bags"
  encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
  run_list:
    - recipe[ssl_certificate_test::default]
  attributes:
- name: subject_alternate_names
  data_bags_path: "test/kitchen/data_bags"
  encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
  run_list:
    - recipe[ssl_certificate_test::subject_alternate_names]
  attributes:
- name: intermediate_chain
  data_bags_path: "test/kitchen/data_bags"
  encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
  run_list:
    - recipe[ssl_certificate_test::intermediate_chain]
  attributes:
- name: with_ca
  data_bags_path: "test/kitchen/data_bags"
  encrypted_data_bag_secret_key_path: "test/kitchen/encrypted_data_bag_secret"
  run_list:
    - recipe[ssl_certificate_test::self_signed_with_ca_certificate]
  attributes:
